export default {
  person: "person",
  lock: "lock-closed",
  eye: "eye",
  eye_off: "eye-off",
  back: "arrow-back",
  email: "mail",
  phone: "call",
  address: "location",
  person_add: "person-add",
  notification: "notifications",
  account: "person-circle",
  search: "search",
  home: "home",
  cart: "cart",
  favourite: "heart",
  order: "document",
  heart: "heart-outline",
  heart_red: "heart",
  close: "close",
  add: "add",
  remove: "remove",
  chevron_forward: "chevron-forward",
  albums: "albums",
  trash: "trash",
  images:"images",
  checkmark:"checkmark",
  cash:"cash",
  card:"card",
};
