export default {
  titlePage1: "Câu chuyện này là của chúng mình",
  titlePage2: "Một bầu trời kiến thức",
  titlePage3: "Hãy nhanh tay đặt mua sản phẩm nào",
  contentPage1:
    "PolyLib được thành lập vào năm 2023, bắt nguồn từ nhu cầu của sinh viên Việt Nam. Mục tiêu của chúng mình là có thể phục vụ và góp phần phát triển cộng đồng sinh viên bằng cách đọc nhiều sách hơn mỗi ngày, và giúp văn hóa  đọc sách của người dân Việt Nam trở nên phát triển hơn.",
  contentPage2:
    "Đến với chúng tôi các bạn sẽ được tận hưởng những cuốn sách bay nhất của các tác giả nổi tiếng nhất trong nước lẫn quốc tế, qua đó độc giả sẽ được trau dồi những kiến thức rất bổ ích cho bản thân.",
  contentPage3:
    "Còn chần chờ gì nữa mà không nhanh tay đặt những sản phẩm tốt nhất bên thư viện chúng tôi, chắc chắn sẽ có những ưu đãi rất lớn dành cho các bạn",
  bo_qua: "Bỏ qua",
  dang_nhap: "Đăng nhập",
  dang_ky: "Đăng ký",
  remember_password: "Lưu mật khẩu?",
  forget_password: "Quên mật khẩu?",
  sign_in: "Login",
  sign_up: "Sign up",
  dont_have_account: "Don't have an account",
  already_an_account: "Already an account",
  hey: "Hey,",
  search: "Tìm kiếm sản phẩm mà bạn muốn tìm...",
  tac_gia_noi_bat: "Tác giả nổi bật",
  tac_pham_noi_bat: "Tác phẩm nổi bật",
  sach_lien_quan: "Sách liên quan",
  them_vao_gio_hang: "Thêm vào giỏ hàng",
  tiep_tuc: "Tiếp tục",
  tong_thanh_toan: "Tổng thanh toán",
  tong_tien: "Tổng tiền",
  tat_ca: "Tất cả",
  huy: "Hủy",
  co: "Có",
  goi_y_cho_ban: "Gợi ý cho bạn",
  loai_sach: "Loại sách",
  loai_san_pham: "Loại sản phẩm",
  san_pham_ban_chay: "Sản phẩm bán chạy",
  sach_ban_chay: "Sách bán chạy",
  thong_tin_tac_gia: "Thông tin tác giả",
  thong_tin_sach: "Thông tin sách",
  thong_tin_san_pham: "Thông tin sản phẩm",
  sach_cua: "Sách của",
  yeu_thich: "Yêu thích",
  textTitleReply:
    "Vui lòng để lại góp ý của bạn tại đây để chúng tôi có thể cải thiện ứng dụng và phục vụ bạn tốt hơn",
  gui: "Gửi",
  thong_bao: "Thông báo",
  ho_so: "Hồ sơ",
  doi_mat_khau: "Đổi mật khẩu",
  dieu_khoan: "Điều khoản",
  xoa_tai_khoan: "Xóa tài khoản",
  dang_xuat: "Đăng xuất",
  xac_nhan: "Xác nhận",
  thay_doi_thong_tin: "Thay đổi thông tin",
  dieu_khoan: "Điều khoản",
  hoi_dang_xuat: "Bạn có chắc chắn muốn đăng xuất không?",
  hoi_xoa_tai_khoan: "Bạn có chắc chắn muốn xóa tài khoản không?",
  gio_hang_sach: "Giỏ hàng sách",
  gio_hang_san_pham: "Giỏ hàng sản phẩm",
  hoi_thao_tac: "Bạn muốn thực hiện thao tác nào?",
  mua_sach: "Mua sách",
  muon_sach: "Mượn sách",
  mua_san_pham: "Mua sản phẩm",
  dia_chi_nhan_hang: "Địa chỉ nhận hàng",
  mua_tai_quan: "Mua tại cửa hàng",
  thay_doi: "Thay đổi",
  thoi_han: "Thời hạn",
  thu_tuc_thanh_toan: "Thủ tục thanh toán",
  phuong_thuc_thanh_toan: "Phương thức thanh toán",
  danh_sach_muon: "Danh sách mượn",
  danh_sach_dat_mua: "Danh sách đặt mua",
  them_dia_chi: "Thêm địa chỉ bạn muốn nhận hàng",
  hoi_nhanh_hang: "Bạn muốn nhận hàng ở đâu?",
  tien_mat: "Tiền mặt",
  chuyen_khoan: "Chuyển khoản",
  ngay_muon: "Ngày mượn",
  ngay_mua: "Ngày mua",
  ngay_het_han: "Ngày hết hạn",
  so_luong_san_pham: "Số lượng sản phẩm",
  so_tien: "Số tiền",
  phi_van_chuyen: "Phí vận chuyển",
  tai_hoa_don: "Tải hóa đơn chuyển tiền",
  chi_tiet_don_hang: "Chi tiết đơn hàng",
  da_chuyen_khoan: "Đã chuyển khoản",
  tien_mat: "Tiền mặt",
  xem_van_chuyen: "Xem đơn hàng",
  cam_on_ban_da: "Cảm ơn bạn đã",
  dat_hang_ben_thu_vien: "Đặt hàng bên thư viện",
  sach_mua: "Sách mua",
  sach_muon: "Sách mượn",
  san_pham_mua: "Sản phẩm mua",
  ma_don_hang:"Mã đơn hàng",
  so_luong_sach:"Số lượng sách",
  so_luong_sp:"Số lượng SP",
  ngay_dat_hang:"Ngày đặt hàng",
  chi_tiet:"Chi tiết",
  ngay_muon:"Ngày mượn",
  ngay_het_han:"Ngày hết hạn",
  cuon_sach_duoc_ban:"cuốn sách được bán",
  cuon_sach_duoc_muon:"cuốn sách được mượn",
  tac_gia:"Tác giả",
  ngay_sinh:"Ngày sinh",
  quoc_tich:"Quốc tịch",
  san_pham_lien_quan:"Sản phẩm liên quan",
  tat_ca_tac_gia:"Tất cả tác giả",
  thong_bao_sach_cua_tac_gia:"Hiện tại thư viện chưa có sách của tác giả"
};
