export default {
  DATA_MEMBER: "https://dyxzsq-2102.csb.app/Member/dataMember",
  ADD_MEMBER: `https://dyxzsq-2102.csb.app/Member/addMemberInApp`,
  UPDATE_MEMBER: `https://dyxzsq-2102.csb.app/member/updateMemberInApp`,
  DATA_LOAN_SLIP: "https://dyxzsq-2102.csb.app/index/dataLoanSlip",
  DATA_BOOK: "https://dyxzsq-2102.csb.app/index/dataBook",
  DATA_AUTHOR: "https://dyxzsq-2102.csb.app/index/dataAuthor",
  DATA_SALES_SLIP: "https://dyxzsq-2102.csb.app/index/dataSalesSlip",
  DATA_BILL: "https://dyxzsq-2102.csb.app/index/dataBill",
  DATA_BOOK_CATEGORY: "https://dyxzsq-2102.csb.app/index/dataBookCategory",
  DATA_GOODS_CATEGORY: "https://dyxzsq-2102.csb.app/index/dataGoodsCategory",
  DATA_GOODS: "https://dyxzsq-2102.csb.app/index/dataGoods",
  DATA_LIKE_PRODUCT: "https://dyxzsq-2102.csb.app/index/dataLikeProduct",
  DELETE_LIKE_PRODUCT: `https://dyxzsq-2102.csb.app/index/deleteLikeProductInApp?_id=`,
  ADD_LIKE_PRODUCT: `https://dyxzsq-2102.csb.app/index/addLikeProductInApp`,
  DATA_DELIVERY_ADDRESS:
    "https://dyxzsq-2102.csb.app/index/dataDeliveryAddress",
  ADD_REPLY: `https://dyxzsq-2102.csb.app/repliesFromUser/addRepliesFromUser`,
  ADD_SHOPPING_CART_BOOK: `https://dyxzsq-2102.csb.app/index/addShoppingCartBookInApp`,
  ADD_SHOPPING_CART_GOODS: `https://dyxzsq-2102.csb.app/index/addShoppingCartGoodsInApp`,
  DELETE_SHOPPING_CART_BOOK: `https://dyxzsq-2102.csb.app/index/deleteShoppingCartBookInApp?_id=`,
  DELETE_SHOPPING_CART_GOODS: `https://dyxzsq-2102.csb.app/index/deleteShoppingCartGoodsInApp?_id=`,
  DATA_CART_GOODS: "https://dyxzsq-2102.csb.app/index/dataShoppingCartGoods",
  DATA_CART_BOOK: "https://dyxzsq-2102.csb.app/index/dataShoppingCartBook",
  ADD_DELIVERY_ADDRESS: `https://dyxzsq-2102.csb.app/index/addDeliveryAddress`,
  ADD_SALES_SLIP: `https://dyxzsq-2102.csb.app/salesSlip/addSalesSlipInApp`,
  ADD_LOAN_SLIP: `https://dyxzsq-2102.csb.app/loanSlip/addLoanSlipInApp`,
  ADD_BILL: `https://dyxzsq-2102.csb.app/bill/addBillInApp`,
  DATA_LIBRARIAN: "https://dyxzsq-2102.csb.app/index/dataLibrarian",
  DATA_RULES: "https://dyxzsq-2102.csb.app/index/dataRules",
};
